INSERT IGNORE INTO SchemaStatus (scriptName, schemaStatus) VALUES ('2024_01_04_drop_unused_tables.sql', 'ONGOING');

DROP TABLE IF EXISTS Pod;
DROP TABLE IF EXISTS PHPSession;
DROP TABLE IF EXISTS Log4Stat;
DROP TABLE IF EXISTS Particle;
DROP TABLE IF EXISTS EMMicroscope;
DROP TABLE IF EXISTS DataReductionStatus;
DROP TABLE IF EXISTS SAFETYREQUEST;
DROP TABLE IF EXISTS SAMPLECELL;
DROP TABLE IF EXISTS SAMPLEEXPOSUREUNIT;
DROP TABLE IF EXISTS SAXSDATACOLLECTIONGROUP;
DROP TABLE IF EXISTS WorkflowStep;
DROP TABLE IF EXISTS WorkflowType;

ALTER TABLE GridInfo
  DROP CONSTRAINT IF EXISTS GridInfo_ibfk_1
  -- , DROP COLUMN IF EXISTS workflowMeshId -- cannot drop yet because dbserver
;
DROP TABLE IF EXISTS WorkflowMesh;

ALTER TABLE DataCollectionGroup
  DROP CONSTRAINT IF EXISTS DataCollectionGroup_ibfk_3,
  DROP COLUMN IF EXISTS workflowId;
DROP TABLE IF EXISTS Workflow;

UPDATE SchemaStatus SET schemaStatus = 'DONE' WHERE scriptName = '2024_01_04_drop_unused_tables.sql';
