name: Build database

on: 
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:10.8
        env:
          MYSQL_USER: test
          MYSQL_PASSWORD: test
          MYSQL_DATABASE: ispyb_build
          MYSQL_ROOT_PASSWORD: rootpassword
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v3
      - name: Build database
        run: |
          cp .my.example.cnf .my.cnf
          bash build.sh

      - name: Regenerate sql files
        run: |
          cd bin
          bash backup.sh ../schemas/ispyb/
          rm ../.my.cnf

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            commit-message: Update database sql files
            title: Update database sql files
            body: |
              This is an automated pull request to update the ISPyB database sql files
              Before merging this pull request you may want to:
              * [ ] Update `HISTORY.md` to reflect the changes in this pull request
            branch: update-schema-sql
            branch-suffix: short-commit-hash
